version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox flake8 pytest-cov
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox

      - run:
          name: run flake8
          command: |
              . venv/bin/activate
              git diff HEAD $(git merge-base HEAD origin/master)  | flake8 --diff
      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            pip install -e .
            py.test --cov=. --cov-fail-under=100
      - run:
          name: upload coverage report
          command: |
            . venv/bin/activate
            pip install codecov
            codecov
